name: hymet_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl
  - python=3.8
  - mash
  - minimap2
  - wget
  - pandas
  - numpy
  - pip
  - biopython
  - csvkit
  - bc
  - unzip
